# ... deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: app
          image: orders:1.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: movie-db-config  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: host          
---
# ... service
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer